name: classes
main: fr.Nofax354.main.Main
version: 0.1
description: classes
author: Nofax354
commands:
   dungeon:
      description: go to dungeon
      usage: /dungeon
   dungeons:
      description: got to dungeons map
      usage: /dungeons
      permission: dungeon.dungeons